// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX-s4o2ebXeHU5_krxUZsFZ9wE-5e3uCo',
    appId: '1:1081112030277:web:0598326c83bdd5591fc72c',
    messagingSenderId: '1081112030277',
    projectId: 'nutrimedai',
    authDomain: 'nutrimedai.firebaseapp.com',
    storageBucket: 'nutrimedai.firebasestorage.app',
    measurementId: 'G-C4ZZBY9B8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1HWjWstyY1SMpAU0tyNUahfqmVy7SeOI',
    appId: '1:1081112030277:android:9d0d101df4fa64f81fc72c',
    messagingSenderId: '1081112030277',
    projectId: 'nutrimedai',
    storageBucket: 'nutrimedai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhfV_y81qVjCngBjJFgt80-aldWe-ws2E',
    appId: '1:1081112030277:ios:925a4686e34ef8731fc72c',
    messagingSenderId: '1081112030277',
    projectId: 'nutrimedai',
    storageBucket: 'nutrimedai.firebasestorage.app',
    iosBundleId: 'com.example.nutrimedai',
  );
}
